config/routes.rb
Rails.application.routes.draw do
  resources :game_players, except: [:edit, :update]
  resources :game_questions
  resources :games do
    member do
      get :players, to: 'games#players'
      get :players_answered, to: 'games#players_answered'
    end
  end
  resources :questions do
    collection do
      post :import
    end
  end

  root to: 'dashboard#index'
  get 'dashboard/index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :episodes do
    resources :created_episodes, only: [:show]
    resources :host_question_episodes, only: [:show, :update]
    resources :host_answer_episodes, only: [:show]
    resources :host_bonus_episodes, only: [:show, :update] do 
      member do
        patch "higher"
        patch "lower"
      end
    end
    resources :host_table_episodes, only: [:show]
    resources :host_leaderboard_episodes, only: [:show]
    resources :player_board_episodes, only: [:show, :update]    
    resources :finished_episodes, only: [:show]
  end  
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.where(user: current_user)
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
    redirect_to question_path(@question) unless @question.user == current_user
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    @question.user_id = current_user.id

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: "Question was successfully created." }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: "Question was successfully updated." }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: "Question was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def import
    flash_import_errors Question.import(params[:file], current_user.id)

    redirect_to questions_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_question
    @question = Question.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def question_params
    params.require(:question).permit(:question, :answer, :is_public)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<% if question.errors.any? %>
  <% question.errors.full_messages.each do |message| %>
  <div class="alert alert-danger" role="alert">
    <%= message %>
  </div>
  <% end %>
<% end %>
<%= form_with(model: question, local: true) do |form| -%>
<div class="card">
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
      <div class="form-group">
        <%= form.label :question, class: "font-weight-bold" %>
        <%= form.text_field :question, placeholder: "Enter question", class: "form-control" %>
      </div>
    </li>
    <li class="list-group-item">
      <div class="form-group">
        <%= form.label :answer, class: "font-weight-bold" %>
        <%= form.text_field :answer, placeholder: "Enter answer", class: "form-control" %>
      </div>
    </li>
    <li class="list-group-item">
      <div class="form-group">
        <%= form.label :is_public, class: "font-weight-bold" %>
        <%= form.check_box :is_public, placeholder: "Enter is_public", class: "pull-left" %>
      </div>
    </li>
  </ul>
  <div class="card-footer">
    <%= link_to "Cancel", question, class: 'btn btn-outline-secondary float-left' if question.persisted? %>
    <%= link_to "Cancel", questions_path, class: 'btn btn-outline-secondary float-left' if !question.persisted? %>
    <%= form.submit "Save", class: "btn btn-primary float-right" if question.persisted? %>
    <%= form.submit "Create", class: "btn btn-primary float-right" if !question.persisted? %>
  </div>
</div>
<% end %>

app/views/questions/edit.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item"><%= link_to "Questions", questions_path %></li>
  <li class="breadcrumb-item"><%= link_to @question.id, @question %></li>
  <li class="breadcrumb-item active">Edit</li>
</ol>

<%= render 'form', question: @question %>

app/views/questions/index.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item active mr-auto">Questions</li>
</ol>
<%= link_to "Add New Question", new_question_path %>
<div class="card-columns">
  <% @questions.each do |question| %>
    <div class="card card mb-4">
      <div class="card-body">
        <h5 class="card-title"><%= link_to question.question, question %></h5>
        <p class="small">Question added by: <%= question.user.team_name %></p>
        <% if question.is_public %>
          <b>Public</b>
        <% end %>
      </div>
      <% if question.user == current_user %>
        <div class="card-footer">
          <%= link_to "Edit", edit_question_path(question) %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>
<%= render "partials/import_objects", path: import_questions_path %>

app/views/questions/new.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item"><%= link_to "Questions", questions_path %></li>
  <li class="breadcrumb-item active">Add</li>
</ol>

<%= render 'form', question: @question %>

app/views/questions/show.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item"><%= link_to "Questions", questions_path %></li>
  <li class="breadcrumb-item active mr-auto"><%= @question.id %></li> 
</ol>
<div class="card">
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
      <p class="font-weight-bold">Question</p>
      <p class="font-weight-normal"><%= @question.question %></p>
    </li>
    <li class="list-group-item">
      <p class="font-weight-bold">Answer</p>
      <p class="font-weight-normal"><%= @question.answer %></p>
    </li>
    <li class="list-group-item">
      <p class="font-weight-bold">Is public</p>
      <p class="font-weight-normal"><%= @question.is_public %></p>
    </li>
    <li class="list-group-item">
      <p class="font-weight-bold">User</p>
      <p class="font-weight-normal"><%= @question.user %></p>
    </li>
  </ul>
</div>