config/routes.rb
Rails.application.routes.draw do
  resources :game_players, except: [:edit, :update]
  resources :game_questions
  resources :games do
    member do
      get :players, to: 'games#players'
      get :players_answered, to: 'games#players_answered'
    end
  end
  resources :questions do
    collection do
      post :import
    end
  end

  root to: 'dashboard#index'
  get 'dashboard/index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :episodes do
    resources :created_episodes, only: [:show]
    resources :host_question_episodes, only: [:show, :update]
    resources :host_answer_episodes, only: [:show]
    resources :host_bonus_episodes, only: [:show, :update] do 
      member do
        patch "higher"
        patch "lower"
      end
    end
    resources :host_table_episodes, only: [:show]
    resources :host_leaderboard_episodes, only: [:show]
    resources :player_board_episodes, only: [:show, :update]    
    resources :finished_episodes, only: [:show]
  end  
end

app/controllers/episodes/created_episodes_controller.rb
class Episodes::CreatedEpisodesController < ApplicationController
  before_action :authenticate_user!

  def show
    @game = Game.find_by(id: params[:id])
  end
end

app/controllers/episodes/finished_episodes_controller.rb
class Episodes::FinishedEpisodesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_finish_state

  def show
    @game = Game.find_by(id: params[:id])
    @game_players = GamePlayer.where(game: @game).order(total_points: :desc)
    ActionCable.server.broadcast "game_channel", content: @game.id
  end

  private

  def set_finish_state
    game = Game.find_by(id: params[:id])
    return if game.game_state == GameState::FINISHED

    game.game_state = GameState::FINISHED
    game.is_complete = true
    game.save
  end
end

app/controllers/episodes/host_answer_episodes_controller.rb
class Episodes::HostAnswerEpisodesController < ApplicationController
  before_action :authenticate_user!
  before_action :allocate_points_and_set_game_state

  def show
    @game = Game.find_by(id: params[:id])
    answer = @game.current_game_question.question.answer

    @game_player_question_answers = GamePlayerQuestionAnswer.eager_load(
      game_player: :user
    ).where(
      game_question_id: @game.current_game_question_id
    ).order(Arel.sql("ABS(COALESCE(answer,0) - #{answer})"), created_at: :asc)
  end

  private

  def allocate_points_and_set_game_state
    game = Game.find_by(id: params[:id])
    return if game.game_state == GameState::QUESTION_ANSWER

    game_question = game.current_game_question

    game_player_question_answers = GamePlayerQuestionAnswer.where(
      game_question_id: game.current_game_question_id
    ).order(Arel.sql("ABS(COALESCE(answer,0) - #{game_question.question.answer})"), created_at: :asc)

    game_question.user_id = game_player_question_answers[0].game_player.user_id
    game_question.save

    game_player_question_answers.each_with_index do |gpqa, i|
      gpqa.points = GamePoint::QUESTION_FIRST if i.zero?
      gpqa.points = GamePoint::QUESTION_SECOND if i == 1
      gpqa.points = GamePoint::QUESTION_THIRD if i == 2
      gpqa.points = GamePoint::QUESTION_FOURTH if i == 3
      gpqa.points = GamePoint::QUESTION_NO_SCORE if i >= 4

      gpqa.points += GamePoint::QUESTION_EXACT_MATCH if gpqa.answer == game_question.question.answer

      gpqa.save
    end

    game.update(game_state: GameState::QUESTION_ANSWER)
  end
end

app/controllers/episodes/host_bonus_episodes_controller.rb
class Episodes::HostBonusEpisodesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_game_state

  def show
    @game = Game.find_by(id: params[:id])
    @cards = @game.current_game_question.current_cards
    @shown_cards = @game.current_game_question.current_card
    @last_guess_correct = @game.current_game_question.last_guess_correct
  end

  def higher
    @game = Game.find_by(id: params[:id])
    @question = @game.current_game_question
    @question.last_guess_correct = next_card_is_higher
    update_question_state
  end

  def lower
    @game = Game.find_by(id: params[:id])
    @question = @game.current_game_question
    @question.last_guess_correct = next_card_is_lower
    update_question_state
  end

  private

  def update_question_state
    next_card = (@question.current_card + 1)
    if !@question.last_guess_correct && next_card < 5
      @question.user_id = next_user
    end
    @question.current_card = next_card

    @question.save
    redirect_to episodes_host_bonus_episode_path(@game.id)
  end

  def set_game_state
    game = Game.find_by(id: params[:id])
    return if game.game_state == GameState::QUESTION_BONUS

    game.update(game_state: GameState::QUESTION_BONUS)
  end

  def next_card_is_higher
    current_card_rank, next_card_rank = ranks
    next_card_rank > current_card_rank
  end

  def next_card_is_lower
    current_card_rank, next_card_rank = ranks
    next_card_rank < current_card_rank
  end

  def ranks
    current_card = @question.current_cards[@question.current_card]
    next_card = @question.current_cards[@question.current_card + 1]
    current_card_rank = card_order.index(current_card[0])
    next_card_rank = card_order.index(next_card[0])
    if current_card_rank == next_card_rank
      current_card_rank = suit_order.index(current_card[1])
      next_card_rank =  suit_order.index(next_card[1])
    end

    return current_card_rank, next_card_rank
  end

  def next_user
    game_player_question_answers = GamePlayerQuestionAnswer.where(
      game_question_id: @game.current_game_question_id
    ).order("ABS(COALESCE(answer,0) - #{@question.question.answer})", created_at: :asc)

    index = game_player_question_answers.index { |gpqa| gpqa.game_player.user_id == @question.user_id }

    next_user = game_player_question_answers[index + 1].game_player.user_id if game_player_question_answers[index + 1]
    next_user = game_player_question_answers[0].game_player.user_id unless game_player_question_answers[index + 1]

    next_user
  end

  def card_order
    %w[2 3 4 5 6 7 8 9 t j q k a]
  end

  def suit_order
    %w[c d h s]
  end
end

app/controllers/episodes/host_leaderboard_episodes_controller.rb
class Episodes::HostLeaderboardEpisodesController < ApplicationController
  before_action :authenticate_user!
  before_action :allocate_points_and_set_game_state

  def show
    @game = Game.find_by(id: params[:id])
    @game_player_question_answers = GamePlayerQuestionAnswer.eager_load(
      game_player: :user
    ).where(
      game_question_id: @game.current_game_question_id
    ).order("COALESCE(points,0) + COALESCE(bonus_points, 0) DESC")
    @game_players = GamePlayer.where(game: @game).order(total_points: :desc)
  end

  private

  def allocate_points_and_set_game_state
    game = Game.find_by(id: params[:id])
    return if game.game_state == GameState::QUESTION_LEADERBOARD

    game.update(game_state: GameState::QUESTION_LEADERBOARD)
  end
end

app/controllers/episodes/host_question_episodes_controller.rb
class Episodes::HostQuestionEpisodesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_next_question

  def show
    @game = Game.find_by(id: params[:id])
    ActionCable.server.broadcast "game_channel", { content: @game.id }
  end

  private

  def set_next_question
    game = Game.find_by(id: params[:id])
    return if game.game_state == GameState::QUESTION_PLAY

    question = Question.where(is_public: game.use_public_questions).or(Question.where(user: current_user)).where.not(id: GameQuestion.pluck(:question_id)).sample
    game_question = GameQuestion.create(game: game, question: question)
    game.update(game_state: GameState::QUESTION_PLAY, current_game_question: game_question, question_number: game.question_number + 1)
  end
end

app/controllers/episodes/host_table_episodes_controller.rb
class Episodes::HostTableEpisodesController < ApplicationController
  before_action :authenticate_user!
  before_action :allocate_points_and_set_game_state

  def show
    @game = Game.find_by(id: params[:id])
    @game_player_question_answers = GamePlayerQuestionAnswer.eager_load(
      game_player: :user
    ).where(
      game_question_id: @game.current_game_question_id
    ).order("COALESCE(points,0) + COALESCE(bonus_points, 0) DESC")
    @game_players = GamePlayer.where(game: @game).order(total_points: :desc)
  end

  private

  def allocate_points_and_set_game_state
    game = Game.find_by(id: params[:id])
    return if game.game_state == GameState::QUESTION_TABLE

    game_question = game.current_game_question
    game_player = GamePlayer.find_by(game: game, user: game_question.user)

    if game_question.last_guess_correct
      game_player_question_answer = GamePlayerQuestionAnswer.find_by(game_question: game_question, game_player: game_player)
      game_player_question_answer.bonus_points = GamePoint::BONUS_FIVE if game_question.current_card == 5
      game_player_question_answer.bonus_points = GamePoint::BONUS_FOUR if game_question.current_card == 4
      game_player_question_answer.bonus_points = GamePoint::BONUS_THREE if game_question.current_card == 3
      game_player_question_answer.bonus_points = GamePoint::BONUS_TWO if game_question.current_card == 2
      game_player_question_answer.bonus_points = GamePoint::BONUS_ONE if game_question.current_card == 1

      game_player_question_answer.save
    else
      game_player_question_answer = GamePlayerQuestionAnswer.where(game_question: game_question).where.not(game_player: game_player)
      game_player_question_answer.each do |gpqa|
        gpqa.bonus_points = GamePoint::BONUS_OTHERS
        gpqa.save
      end
    end

    update_player_points(game, game_question)

    game.update(game_state: GameState::QUESTION_TABLE)
  end

  def update_player_points(game, game_question)
    game_players = GamePlayer.where(game: game)
    game_players.each do |gp|
      game_player_question_answer = GamePlayerQuestionAnswer.find_by(game_question: game_question, game_player: gp)
      gp.total_points = (gp.total_points || 0) + (game_player_question_answer.points || 0) + (game_player_question_answer.bonus_points || 0) if game_player_question_answer
      gp.save
    end
  end
end

app/controllers/episodes/player_board_episodes_controller.rb
class Episodes::PlayerBoardEpisodesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_game

  def show
    @game_player = GamePlayer.find_by(game: @game, user: current_user)
    @game_current_answer = GamePlayerQuestionAnswer.find_by(game_player: @game_player, game_question_id: @game.current_game_question_id)
    @all_players = GamePlayer.where(game: @game).order(total_points: :desc)
  end

  def update
    game_player_id = params[:game_player_id]
    game_question_id = params[:game_question_id]
    answer = params[:answer]

    game_question_answer = GamePlayerQuestionAnswer.find_or_create_by(game_player_id: game_player_id, game_question_id: game_question_id)
    game_question_answer.answer = answer
    game_question_answer.save

    redirect_to episodes_player_board_episode_path(@game)
  end

  private

  def set_game
    @game = Game.find_by(id: params[:id])
  end
end

app/views/episodes/host_bonus_episodes/show.html.erb
<%= render 'shared/play_header', game: @game %>
<div class="card shadow p-2">
  <div class="card-body">
    <h1 class="text-success">Bonus Round - *** <%= @game.current_game_question.user.team_name if @game.current_game_question.user %> *** team controls the board</h1>
    <br>
    <div class="playingCards fourColours faceImages">
      <p>Aces high, same card suit order: clubs (lowest), followed by diamonds, hearts, and spades (highest). </p>
      <div class="row">
        <div class="col-lg-12">
          <% if !@last_guess_correct.nil? %>
            <% if  @shown_cards == 5 %>
              <% if @last_guess_correct %>
                <h1 class="text-success">Well Done! You Collect Maximum Bonus Points!</h1>
              <% else %>
                <h1 class="text-danger">Oh No! You have blown it. 10 points to everyone else!</h1>
              <% end %>            
            <% else %>
              <% if @last_guess_correct %>
                <h1 class="text-success">Correct! Dare to Play On?</h1>
              <% else %>
                <h1 class="text-danger">Wrong! Wrong! Control Goes to <%= @game.current_game_question.user.team_name %></h1>
              <% end %>            
            <% end %>
          <% end %>
        </div> 
      </div>      
      <div class="row">
        <div class="col-lg-1">
        </div>
        <% @cards.each_with_index do |card, index| %>
          <% base_css = "card back" if index > @shown_cards %>
          <% base_css = "card rank-#{card[0] == "t" ? "10" : card[0]} #{SuitProperty.find_by_code(card[1])[:css_suit]} " if index <= @shown_cards %>
          <div class="col-lg-1 text-center">
            <div class="<%= base_css %>">
                <span class="rank"><%= card[0] == "t" ? "10" : card[0].upcase %></span>
                <span class="suit">&<%= SuitProperty.find_by_code(card[1])[:span_suit] %>;</span>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-1">
        <h3 class="text-primary">Points:</h3>
      </div>
      <div class="col-lg-1 text-center">
        <h3 class="text-primary">0</h3>
      </div>
      <div class="col-lg-1 text-center">
        <h3 class="text-primary">5</h3>
      </div>
      <div class="col-lg-1 text-center">
        <h3 class="text-primary">10</h3>
      </div>
      <div class="col-lg-1 text-center">
        <h3 class="text-primary">20</h3>
      </div>
      <div class="col-lg-1 text-center">
        <h3 class="text-primary">30</h3>
      </div>
      <div class="col-lg-1 text-center">
        <h3 class="text-primary">50</h3>
      </div>                       
    </div>
    <div class="row">
      <div class="col-lg-1 offset-lg-3">
        <button data-controller="card" data-id="<%= @game.id %>" data-action="click->card#higher" class="btn btn-outline-info waves-effect btn-lg">Higher</button>
      </div>
      <div class="col-lg-1">
        <button data-controller="card" data-id="<%= @game.id %>" data-action="click->card#lower" class="btn btn-outline-info waves-effect btn-lg">Lower</button>  
      </div>
      <div class="col-lg-1  offset-lg-2">
        <%= link_to "Take the Points", episodes_host_table_episode_path(@game.id), class: "btn btn-success" if @last_guess_correct %>
        <%= link_to "Finish Round", episodes_host_table_episode_path(@game.id), class: "btn btn-success" if !@last_guess_correct && @shown_cards == 5 %>
      </div>      
    </div>
  </div>
</div>