config/routes.rb
Rails.application.routes.draw do
  resources :game_players, except: [:edit, :update]
  resources :game_questions
  resources :games do
    member do
      get :players, to: 'games#players'
      get :players_answered, to: 'games#players_answered'
    end
  end
  resources :questions do
    collection do
      post :import
    end
  end

  root to: 'dashboard#index'
  get 'dashboard/index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :episodes do
    resources :created_episodes, only: [:show]
    resources :host_question_episodes, only: [:show, :update]
    resources :host_answer_episodes, only: [:show]
    resources :host_bonus_episodes, only: [:show, :update] do 
      member do
        patch "higher"
        patch "lower"
      end
    end
    resources :host_table_episodes, only: [:show]
    resources :host_leaderboard_episodes, only: [:show]
    resources :player_board_episodes, only: [:show, :update]    
    resources :finished_episodes, only: [:show]
  end  
end

app/views/shared/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
  <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %> alert-dismissible fade show" role="alert">
    <%= content_tag :div, msg %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <% end %>
<% end %>

app/views/shared/_metatags.html.erb
<title><%=h sanitize current_title %></title>
<link rel="canonical" href="<%=h current_url %>" />
<% if content_for?(:image) -%>
<link rel="image_src" href="<%= content_for(:image) %>">
<% end %>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="robots" content="<%=h content_for_or(:robot, 'INDEX,FOLLOW') %>"/>
<meta name="description" content="<%=h content_for_or(:description, '') %>"/>
<meta name="keywords" content="<%=h content_for_or(:keywords, '') %>">
<meta name="theme-color" content="#777777">
<meta property="og:url" content="<%=h current_url %>" />
<meta property="og:site_name" content="<%= current_site %>" />
<meta property="og:type" content="<%=h content_for_or(:type, 'website') %>">
<meta property="og:title" content="<%=h current_title %>" />
<meta property="og:description" content="<%=h content_for_or(:description, '') %>" />
<% if content_for?(:image) -%>
<meta property="og:image" content="<%= content_for(:image) %>" />
<% end %>
<% if content_for?(:video) -%>
<meta property="og:video" content="<%= content_for(:video) %>" />
<% end %>
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="<%= ENV['APP_TWITTER'] %>"/>
<meta name="twitter:creator" content="<%= ENV['APP_TWITTER'] %>"/>
<meta name="twitter:title" content="<%=h current_title %>"/>
<meta name="twitter:description" content="<%=h content_for_or(:description, '') %>"/>
<meta name="twitter:url" content="<%=h current_url %>"/>
<% if content_for?(:image) -%>
<meta name="twitter:image" content="<%= content_for(:image) %>"/>
<% end %>
<%= auto_discovery_link_tag(:rss, content_for(:rss), {title: "RSS Feed"}) if content_for?(:rss) %>
<%= auto_discovery_link_tag(:atom, content_for(:atom), {title: "Atom Feed"}) if content_for?(:atom) %>
<%= stylesheet_link_tag "cards" %>
<%= stylesheet_link_tag "game" %>
<%= stylesheet_pack_tag 'application', preload: true, media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
<%= csrf_meta_tags %>
<%= action_cable_meta_tag %>

app/views/shared/_navbar.html.erb
<nav id="navbar" class="navbar fixed-top navbar-expand-lg navbar-dark bg-secondary">
  <div class="container-fluid">
    <%= link_to current_site, root_path, title: current_site, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Menu">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarContent">
      <ul class="navbar-nav">
        <%= link_to "Questions", questions_path, class: "nav-link" %>
      </ul>
      <ul class="navbar-nav">
        <%= link_to "Games", games_path, class: "nav-link" %>
      </ul>      
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <%= link_to "Change User Details", edit_user_registration_path, method: :get, class: "nav-link" %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
        <% else %>
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_play_header.html.erb
<div class="row">
  <div class="col-lg-8">
    <h1 class="text-info"><%= game.name %></h1>
  </div>
  <div class="col-lg-4 text-right">
    <h4 class="text-secondary">Pin <%= game.pin %></h4>
  </div>
</div>